
project:
  type: website

website:
  title: "Econ 106: Data Analysis in Economics"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: syllabus.qmd
        text: Syllabus
      - text: Lectures
        menu:
          - href: lectures/lecture1.qmd
            text: Lecture 1
          - href: lectures/lecture2.qmd
            text: Lecture 2
      - href: labs/index.qmd
        text: Labs
    right:
      - href: about.qmd
        text: About

format:
  html:
    theme: cosmo
    toc: true
