project:
  type: website
  output-dir: docs
  resources:
    - lectures/
    - lecture-scripts/
    - html-lectures/

website:
  title: "Econ 106"
  navbar:
    left:
      - href: index.qmd
        text: Home
  page-footer:
    center: "© 2024 Veronica Sovero | UC Riverside"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
