---
title: "Lecture 5: Data Visualization with ggplot2"
format: html
---

Econ 1 06

Lecture5

Fall 2024

sli des ad apt ed f rom 

ht t ps: //

jh uda ta scien ce. org

/

t idyve rsecou rse

/ dat avi z.h tml #ab out

-

t his

-

cou rse

-

3 

1

R em i nd er s

L ab 1  is du e S un da y 11 :5 9p m

P oll e ver ywhe re  score s ar e in t h e ca nva sg ra de bo ok (f u ll 

cre di t if  >5 0% co rre ct )

2

h tt ps:/ /

p o lle v.co m

/

vso ve ro

#

ti d ytue sda y

Fo ot b all is 

h ap pe nin g n ow,  

ri gh t?

3

ht tps: //

x. co m

/

ja kek aup p

/s tatu s/12 265 568 134 762 700 80? s= 20

Ou tl i ne

Vi sua li zatio n  Ba ckg r ou n d

In tro d u ctio n t o  g gp lo t2

B asic e lem en t s( da t a,  ae st he ti cs, 

g eo ms

)

co lor a s inf o rma t ion

4

 

re sul ts wi th  f igu re st h at  ar e mo re  comp el ling  an d a ccessib le.

Two  ma in a dva nt ag es o f d at a  visua liza ti on :

F acil it at es compa rison s

He lps id ent if y tre nds

5

W hyg gp l ot2 ?

Re p ro du cib ilit y

Pa r t of th e  

t idy v e rs e

Pr e tt y  

b y d efa u lt

Cu sto mi zab le

ht tp:// vari anc eex plai ned .org /r/w hy

-

I

-

us e

-

gg plo t2/

Bu tfi r st,so m etr u tha bo ut gg pl o t2

7

ea sie stto ge tthe ha ngo f

S imp lev isua liza tion sa re 

ea sie rus ing bas eR

Ba si cEl e me nts ofa D at aV isu al i za ti on

1.

Da ta

: t he d at a you wa nt t o pl ot

2.

L ayo u t

: ma ppi ng vari abl es on t he 

pl ot

3.

Da ta di sp l ay

: h ow you w ant  th e 

da ta t o be vi sual ized (p oin ts,  

li nes,  bars,  et c.)

1 .Sp eci fyd at a

ggp lo t

() :

Cr ea te s a p lot  ob je ct

da ta  

sp ecif ie s wha t d at a  ta bl e 

yo u will u se

O utp ut

:  bla nk p lot  

ggp lo t

(

da ta

= d iam on ds)

mappi ng 

argum ent

specif ies 

what shou

ld

goonthex andy 

axes

x

= x ax isv ariable

y

= y ax isv ariable

aes

()funct ion isrequired 

wheneveryoureference 

specif icv ariables in yourdata

Outpu t

: plot wit haxes, nodata

2 .Sp eci fyL ayo ut

ggplot

(

d a ta

=  di a m o nd s ,  

m a p p i n g

= 

aes

(

x

=  ca ra t ,  

y

=  pr ic e ))

3 .Sp eci fyD a ta Di sp l ay 

re qu ire s:

+

o pe rato r

geo m_ poin t

()

O utp u t

: sca tt erp lot

gg plo t

(

da ta

=di amo nds , 

m app ing

= 

ae s

(

x

=ca rat,

y

=pr ice) ) 

+

ge om _po int

()

g gp lo t2 fun cti on s

ggp lo t

() : cr ea t es a 

g gp lot

o bje ct

aes

( ) f u n ctio n is r e q ui re d  wh e ne ve r  you  r e fe r e n ce 

sp e cific va ria b le s in  yo ur  d a ta

ge om_X X X

() : d ra ws po int s/ lin es e t c.

+

:  ad ds co mpo ne nt s t o p lot

Mod ula rst ruct ure  

Sca tte r Pl ot

g g p l o t

(

d a ta

=  di a m o nd s ,  

m a p p i n g

= 

aes

(

x

=  ca ra t ,

y

=  pr ic e )) 

+

g e o m _ p o i n t

()

13

h tt ps:/ /

p o lle v.co m

/

vso ve ro

D at aE xam pl e

W e ar e g oin g t o wo rk wit h  th e g en de r ga p d at a :

j obs _ge nde r

<

-

re ad _csv

(

"h tt p s: //

ra w. gi th ub use rco nt e nt . com

/

rf o rd at asci en ce

/

t id yt

u esd ay

/ ma st er/ d at a /2 01 9/ 2 01 9

-

03

-

0 5/

jo bs_ ge nd er .csv

"

)

14

ti d ytue sda y

d ata

15

Exe r cise

Cr ea te  a sca tt e r pl ot  wit h 

t ot a l_e ar nin gs

o n t he  x

-

a xis an d 

wa ge _p er cen t_ of _ ma le

o n t he  y

-

a xis

16

Ad j usti n gP l otS ett in gs

col or

: 

co lo r of 1

-

d o bje ct s

fil l

: fillc olor of 2

-

dobjects

li netype

: how liness houldbedrawn(s olid, dashed, dotted, etc. )

shape

: shape ofmarkers insc at terplots

siz e

: how large objec ts appear

alp ha

: transparency of object s(v aluebetw een 0 and 1)

17

Tr an spa re ncy

A dd  arg um en t t o  

ge om _po in t

()

Re du ce t ra nsp ar en cyo f  

p oin t s

I nput

: 

a lp ha

= 0 . 1 

1 /1 0 o pa cit y

Ra ng e:  0

-

1

gg plo t

(

da ta

=di amo nds , 

m app ing

=

ae s

(

x

=ca rat,  

y

=pri ce))  

+

ge om _po int

(

al pha

=0. 1)

C ol o r

Ch ang e poi nt co lors t o blu e 

I np u t

: 

co l or

arg umen t

O utp u t

: b lue p oin ts

C olor refe ren cec har t: 

ht tp:// sap e.in f.us i.ch /qui ck

-

re fere nce /ggp lot2 /co lour

gg plo t

(

da ta

=di amo nds , 

m app ing

= 

ae s

(

x

=ca rat,  

y

=pr ice) )

+

ge om _po int

(

al pha

=0. 1, 

co lor

=" blu e" )

h tt ps:/ /

p o lle v.co m

/

vso ve ro

Exe r cise :sca tte rp l ots an dco l or

20

Y our bos sre quir est hat alls cat terp lots us etri ang les hap esa nd the corn flow er 

to tal_ earn ing s

an d 

w age _pe rcen t_o f_m ale

ac cor ding ly. 

D pl yr

a nd  

g gp lo t

O f t en ti mes yo u wil l 

u se 

d plyr

t o cr ea te  

a n ew d at a  fr am e,  

t he n p lot  t he  re sult s 

u sing  

g gp lot

Re me mbe r t o p ut  in  

t he  na me o f  th e 

n ew d at a f ra me  in 

yo ur 

g gp lot

()

21

ve ry_ goo d_c ut

<

-

di am ond s

% >%

fil ter

(

cu t

==

"

V ery Go od

"

)

gg plo t

(

da ta

= 

ve ry_ goo d_c ut

, 

mapp ing

= 

ae s

(

x

=ca rat,  

y

=pr ice) )

+

ge om _po int

(

al pha

=0. 1, 

co lor

=" blu e" )

D pl yr

a nd  

g gp lo t

O f t en ti mes yo u wil l 

u se 

d plyr

t o cr ea te  a 

n ew d at a f ra me , t h en  

p lot  t he  resu lt s usin g 

g gp lot

t he  re sult s di rect ly in t o 

g gp lot

(r em ovin g t he  

d at a a rg ume nt  in side  

g gp lot

() )

22

di amond s

% >%

fil ter

(

cu t

==

"

V ery Go od

"

)

% >%

gg plo t

(

m app ing

= 

ae s

(

x

=ca rat,  

y

=pr ice) )

+

ge om_po int

(

al pha

=0. 1, 

co lor

=" blu e" )

Exe r cise

Fil te r f or  occu pa ti on si n com pu t er,  e ng ine er ing , a nd  scien ce

cre at e  a scat t e r plo t  of  

t ot a l_e ar nin gs

a nd  

wa ge _p er cen t_ of _ ma le

23

N ext  

u p:L i ne Gr ap hs

L ine  gra ph s ar e pr ob ab ly t he h ar de st g ra ph  to  ge ne ra te  

co rre ct ly (no t  loo k like a  ho t m ess)

To  ge t it  ri gh t,  mo st  da ta  re qu ire sw ran gl ing  (ge t  you r da t a 

re ad y be f ore  

g gp lot

) o r gr ou pin g ( wit hin  

g gp lot

)

24

Ga pm i nd er

D at a

p art  o f 

g ap min de r

p acka ge

Fo r 18 5 

co un tr ies 

in  th e wo rld ,  

t he  pa ckag e p rovi de sva lu es 

f or  lif e e xpe cta ncy,  G DP  pe r 

ca pit a , e ver yye ar  fr om 1 96 0 

t o 2 01 6.

25

lib rar y

(

ds lab s

)

da ta

(

ga pm inde r

)

Fer ti l i tyo ver Ti me

gg plo t

(

da ta

= 

ga pm inde r

, 

m app ing

=

ae s

(

x

=

ye ar, 

y

=fer tility )) 

+

ge om _lin e

()

26

What hap pen ed?

Fer ti l i tyo ver Ti me ( scatte r pl o t)

gg plo t

(

da ta

= 

ga pm inde r

, 

m app ing

=

ae s

(

x

=

ye ar, 

y

=fer tility )) 

+

ge om _po int

()

27

Di spla ying t he d at a 

as a scat t er plo t can  

he lp us f igu re out  

T here a re many 

val ues of  fe rti lit y fo r 

ea ch year (on e fo r 

ea ch coun try)

 

sen se to d raw a 

sin gle l ine t hro ugh a ll 

t hese p oin ts

Fer ti l i tyo ver Ti me ( li n ef or ea ch cou ntr y)

gg plo t

(

da ta

= 

ga pm inde r

, 

m app ing

=

ae s

(

x

=

ye ar, 

y

=fer tility )) 

+

ge om _lin e

(

ae s

(

gr oup

=co untr y))

28

W e nee d to t el l 

gg plo t

t o creat e a li ne 

f or each co unt ry 

usi ng t he gro up 

arg umen t

O k, bu t t oo man yco unt rie s!

Fer ti l i tyo ver Ti me ( li n ef or ea ch cou ntr y)

S outh _A me rica

<

-

ga pm ind er

% >%

fil ter(

re gio n=="S ou thA me ric a"

)

gg plo t

(

da ta

= 

S outh _A mer ica

, 

m app ing

=

ae s

(

x

=

ye ar, 

y

=fer tility )) 

+

ge om _lin e

(

ae s

(

gr oup

=co untr y))

29

F irst , on ly sele ct cou nt ries in So ut h America , t hen  

gg plo t

h tt ps: //

p o lle v. co m

/

vso ve ro

Fer ti l i tyo ver Ti me ( li n ef or ea ch cou ntr y)

ga pm ind er

% >%

fil ter

(

re gio n=="S ou thA me ric a"

)

% >%

gg plo t

(

m app ing

=

ae s

(

x

=

ye ar, 

y

=fer tility )) 

+

ge om _lin e

(

ae s

(

gr oup

=co untr y))

30

W e can use p ipe st o wra ngl e and  

gg plo t

al l at o nce

Exe r cise :l i ne g ra ph s

Cre at e a lin e grap h of o ccupa ti ons in a rchit ect ure a nd en gin eeri ng 

occu pat io ns show ing  

pe rcent _f ema le

by yea r

31

h tt ps:/ /

p o lle v.co m

/

vso ve ro

Fer ti l i tyo ver Ti me ( li n ef or ea ch con ti ne nt)

c o n tin e n t_ s u mma ry

<

-

g a p min d e r

%> %

g ro u p _b y

(

c o n tin e n t, y e a r

)

%> %

s u mma ri ze

(

me a n _ fe rti li ty

=

me a n

(

fe rt il it y,  

n a .rm

=T R UE )

32

W e nee d to co lla pse 

t he da ta t o con ti nen t 

by yea ru sing  

g ro up _b y

() and  

su mm ari ze

()

Fer ti l i tyo ver Ti me ( li n ef or ea ch con ti ne nt)

g g p lo t

(

d a ta

=

co n ti n en t _ sum ma ry

, 

ma p p in g

=

aes

(

x

=

ye a r,  

y

=

me a n _ fe rt il it y

))  

+

g e o m_ li ne

(

aes

(

g ro u p

=co n t in e n t

))

33

T hen w e 

gg plo t

usi ng 

t he gro up arg umen t

Exe r cise

ca lcula t e t he  me an  

p erce nt _ f ema le

b yye ar  an d by 

mi no r_ca t eg or y

f or  occu pa ti on si n com pu t er,  e ng ine er ing  an d 

scie nce

p lot  as a  line  gr ap h

34

C ol o r Ma pp i ng

35

ga pm ind er

% >%

fil ter(

re gio n=="S ou thA me ric a"

) 

% >%

gg plo t

(

m app ing

=

ae s

(

x

=

ye ar, 

y

=fer tility )) 

+

ge om _lin e

(

ae s

(

gr oup

=co untr y

))

ga pm ind er

% >%

fil ter(

re gio n=="S ou thA me ric a"

) 

% >%

gg plo t

(

m app ing

=

ae s

(

x

=

ye ar, 

y

=fer tility )) 

+

ge om _lin e

(

ae s

(

co lor

=co untr y

))

Exe r cise

ca lcula t e t he  me an  

p erce nt _ f ema le

b yye ar  an d by 

mi no r_ca t eg or y

f or  occu pa ti on si n com pu t er,  e ng ine er ing  an d 

scie nce

p lot  as a  line  gr ap h

co lor t h e lin es b y 

mi no r_ca t eg or y

36

h tt ps:/ /

p o lle v.co m

/

vso ve ro