
---
title: "Lecture 1: Introduction to R"
format: html
---

📎 [Download the R script for this lecture](../lecture1.R)

## Econ 1 06

- Da ta An alysi si n 
- Econ omics
- Fal l 2024
- Ba sedo n: 
- ht tps: //
- dat acar pent r y.or g
- /R
- -
- ecol ogy
- -
- l esson/ int ro ducti on
- -
- r
- -
- r stud io. htm l

## Ou tl i ne



## Cla ss O ve rvi ew



## In tro  t o R :



## R

- s
- t ud io
- Co nso le

## O pe ra t ors



## Fu nct io ns



## O bj ect s

- 2

## D at ai se ver yw he re



## In  20 15 t h e he a lt hca re  i nd us t ry  

- a lo ne p ro d uce d
- 1.2 b i lli on c li n i c a l 
- d oc um e n ts
- .

## T h e a mou nt  of t ex t d at a g en er at e d 

- a nn ua lly  (d i g i t a l for ms , s oci a l 
- me d i a ,o nl i ne  po rt al s ,p d f re po rt s , 
- e ma i ls , t ex t me s s a g es )  i s  ev er  
- i n cre as i n g
- H olmes , Da wn E.,  'T he dat a expl osi on', B ig  Data : A Very  Short I nt roducti on,  Ver y Short  Int roducti ons 
- (Oxford , 20 17; onl ine 
- edn
- ,  Oxford Academi c, 23  Nov.  
- 20 17),
- ht tp s: // doi. org /10 .1093 /act rad e/97 801987 7957 5.0 03. 00 01
- )
- 3

## h tt p s: //

- wo l. iza. o rg
- / ar t icles/ b ig
- -
- d at a
- -
- in
- -
- e con omi cs
- 4

## N ee d aj o b? Le ar n ho w tow o rk wi th d ata



## Da t a an al yst:  e mph asi so n 

- b ein g a ble  to  int e rp ret  a nd  
- co mmu nica t e f in din gs 
- (i nsig ht ,  re po rt ing )

## Data li te ra cy i s the ab i li ty  

- of an i nd i v i du alt or e ad,  
- un de r stand , an d
- w or k
- wi th 
- d ata to cr eat eme ani ng fu l 
- i nsi g hts
- 5
- ht t ps :/ /
- w ww . r
- -
- bl o gge rs . co m
- / 202 2/ 04/ t ex t
- -
- an al y si s
- -
- of
- -
- j ob
- -
- de sc r i pt i ons
- -
- f or
- -
- da ta
- -
- s ci e nt i st s
- -
- da ta
- -
- en gi ne er s
- -
- m a ch i ne
- -
- l ea rn i ng
- -
- en gi ne er s
- -
- an d
- -
- da ta
- -
- an al y st s /

## In ten de d Aud i en ce



## S

- tu de nts who want to:

## ser ve asr esearc hassi st ant s



## c onduct em pi ri c alanaly ses



## are i nter ested i nD ata Sci enc ecar eers.



## P re req ui sit es:  Eco n 1 01  (S ta t ist ics)



## No  pri or p ro gra mm ing  exp eri en ce is ne ed ed  

- 6

## C ou r seOb j ecti ve s



## M aste r the ab i li ty t oc olle ct, p r oc ess, i nte r pr et , 

- an aly ze
- r aw
- d ata usi ng R.

## Dev e lop v i sual iz ati on ski lls ne cessar y  to 

- summa ri ze d ata fi nd i ng s

## C ommun i cate fi n di ng st ov ar i ou sau di e nce san d 

- i n v ar io us for mats.
- 7

## W hya re w e usi ng R i n thi sco ur se?

- Ad v antag es of R:

## ‰ ¬}É m ¡¡ T%”6 b¡ % }6€m …¡



## ‰ ¬}Áë ” ¡Ê €}¡” ë% 

- i nd ustr y

## It ha sa lar ge an d act iv e  

- use r co mmuni ty

## M or e of a tr ue 

- p r ogr ammin g lang uag e 
- co mpa re d to Sta ta
- 8

## R vs.P ytho n

- R:

## B uil t fo r s ta t is tics  a nd  d at a  

- a na ly s i s

## B e tt e r at  eco no me t ri cs  an d d a ta  

- v i s ua li za t i on
- Py t ho n:

## B uil t fo r gen e ral

- -
- p urp os e  
- p rog ram min ga n d s o ftw ar e 
- d e ve lo pm en t

## B e tt e r at  ma chi n e le a rni n g

- 9

## R i sa me an s,n ot an en d



## T he go also f thi sc our se ar e

- p lat fo rm
- -
- ag nos t i c

## ‰ ¬} %6‰ Ty6€‰‰ à¡}Ê %‰ TÉ 6É}b ¡…ë Éë … bT… TÌ¡}



## ‰ ¬} Ty6€‰‰ à¡… 6%…¡b‰ }l6Ì ë …lT%”‰ à6€Ìà‰b m6…¡} }¡}

- under ly ing what w e're doi ng andwhy

## Yo ur e v entu al goa l:

- Us e t he ri g ht t oo l for t he j ob

## Yo u wil lli k ely l ear n all the set ools at some p oi nt.

- 10

## Gr ad i ng

- 11
- A ss i g nm en t
- P o in ts
- L a b A ssig n me n ts
- 40
- P o ll E ve rywh e re  
- 10
- P ro je ct M il est o n es
- 30
- F in a l P ro je ct  
- 20
- T OTAL
- 100

## L ab Assi gn m en ts



## L ab a ssig nme nt s:  gi ves you  t he o pp or t un it yt o  pra ct ice t h e 

- d at a skil ls cove red  du rin g le ct ure

## Two  com po ne nt s:  writ e up a nd  R scrip t



## Du e o n S un da ysa t  11 :5 9p m



## I  will d ro p t he  lowe st  lab  score  at  t he  en d of  t he  qu ar te r

- 12

## R ese ar ch Pr oj e ct



## T he go alo f thi sc lass is to gi v e y ou the sk il lsto c ond uc t 

- y ou r own
- sm all
- r ese ar ch pr o je ct.

## T hr ee p ro j ect mi lesto nes wi ll walk y ou thr ou gh th e 

- r ese ar ch pr o cess

## All thr e ewi ll co unt  

- to war d y our  fi nal gr ad e (no d r op s)

## F i nal pr o du ct:



## W ri t eup( ~ 150 0wor ds)



## doc ument at i on( rs cri p ts)

- 13

## E xamples ofS tuden t 

- W ork

## C ha tGP T/ Gen er at ive AI



## I t  is up t o  you w he th er  you w an t t o u se g en er at ive A I  t o he lp  

- yo u wit h yo ur  cod e

## G ui de line s:



## T he cod e has t o use t he t ool sco vered i n lect ure



## You ca nno t use i t f or th e writ t en po rti on of  lab a ssign ment s or 

- rese arch mil est one s

## You n eed t o st at e whe th er you use d it f or you rco de an d how . 

- 15

## Po l l Eve ryw h er e



## I u se Poll Eve rywhe re to  

- en coura ge act ive l earn ing d urin g 
- le ctu re

## My pol ls wil l be ava ila ble h ere 

- wh en t hey go l ive:  
- Po l lE v.co m/v s ove ro

## Po l l Eve ryw h er e



## Ple ase use yo ur 

- ucr
- ema il ad dress t o sign i n (do no t sig n up f or an acco unt )

## You w ill b e redi rect ed t o th e UCR SSO



## L ectu re Qu i zzes( un gr a de d)



## P ost e d on  Can vas f o r you  to  pr act ice a f t er le ct ur e



## Do es n ot  cou nt  t owa rd s you r gr ad e



## Fe el f re e t o a sk Fan  t o re view t h ese  qu est io ns du rin g la b 

- se cti on
- 18

## L ectu re Scr i pt s



## I  po st a ll o f t h e cod e u sed  du rin g le ctu re  as an  R scrip t o n 

- Ca nva s

## Ru nn ing  t he co de  du rin g o r af t er  lect u re wi ll he lp yo u g ain  

- mo re  fa mil iar it yw it h 
- Rst u dio
- 19

## Thi sW ee k:In tr od ucti o nt oR B asi cs



## B ef o re we  cove r mo re b ro ad  to pi csi n da t a a na lysis,  we 

- n ee d t o u nd erst a nd  some  R ba sics

## W e ne ed  t he se bu ild ing  blo cks be f ore  mo ving  on to  da t a 

- wr an glin g,  visu ali zat io n,  et c.
- 20

## C od i ng Go al s

- 1.
- Run c od ewith out er r or s (pr e tty d oab le with 
- C hatG PT
- )
- 2.
- Ru n co de t h at  pr od uce s wha t yo u we re  exp ect in g 
- 3.
- Ru n co de t h at  pr od uce s wha t yo u we re  exp ect in g an d yo u 
- u nd erst a nd
- 21

## Ge tti ng h el p

- 1.
- Re ad  th e e rro r me ssag e.
- 2.
- Tr yso me  on line  re sou rces:

## St ack Ove rfl ow



## Ch at GPT

- (t ype in yo ur code a nd t he erro rme ssage )

## Sla ck 

- 3.
- S t ill st uck?

## Ple ase rea ch out  to myse lf o ryo ur TA (F an Bu)



## Sha re your cod e, d at a, scre ensh ot so f t he erro rme ssage , et c.

- 22

## Exa m pl e: Be C ar efu l w i thTyp os



## Imp l ic it c o nt r ac twi th t he 

- c o mp ut er / sc r ip ti ng  
- l an gua ge:

## C o mpu ter wi ll d o ted io us  

- co mp uta tio n f or y o u.

## In r etur n, y ou w il l be 

- co mp lete l y p reci se in y o ur  
- i ns tru ctio n s

## T yp o sm att er. Casem att er s. 

- d at a_ ro cks
- <
- -
- 2
- ^
- 3
- d at ar ocks
- # > Er ro r in e val( exp r,  
- e nvir
- , 
- e nclo s

## d at ar ocks

- ' n ot  
- f ou nd
- Da t a_ rocks
- # > Er ro r in e val( exp r,  
- e nvir
- , 
- e nclo s

## Da t a_ rocks

- ' 
- n ot  f ou nd
- 23

## W ha ti sR ?R S tud i o?



## R



## a  p ro g r am m in g l an g u a g e +  

- so ft wa re  t h at in te rp r e tsi t

## RS tu di o



## p o p ul ar  so f tw ar e  t o 

- wr ite  R scrip ts a n d in te r act with  
- th e R so ft wa r e

## W e will b e u sing  

- Rst u dio
- in  th is cou rse  
- (h ow eve r you  ne ed t o  inst a ll R in o rd er 
- f or  it t o  run  cor rect ly)
- 24

## R St ud io In ter fa ce

- Sc r ipt
- Co ns o le
- En v iro nm en t
- F il e s
- 25

## RS tu di oCon sole



## Yo uc an  input a nd  

- ex ec utec omma nds  
- di rec tlyinthe co ns o le.

## O utputo fc erta in 

- c omma nd sw ill be 
- di sp la yed i n the 
- c on so le .
- 26
- Co ns o le

## R stu di o

- Scr i pt Ed it or

## Most d at a anal ysi s wi ll r e qu i re  

- se ver al st eps

## T he  scri pt e d it or i s use d  to 

- r ecor d t he  ste ps (command s) 
- w e t ake t oa naly ze ou r d ata
- WR IT E
- 27

## R stu di o

- Scr i pt Ed it or

## Onceyout ypethem in the 

- sc ript ,y ou still needt osend 
- them tothec ons ole toberun.

## S cri pts a re  saved  wi t h t he  .R 

-  ò Uäó
- WR IT E
- R UN
- Ctr l
- -
- En ter
- 28

## C om m en ti ng i nS cri p ts



## R ig no re sth e 

- r est of a li ne 
- af ter a
- #

## wr i te not est o 

- y ou rse lf ab out 
- wha ty ou r  
- co de i s do in g

## co mment sar e 

- au tomati c ally  
- i n gr ee n
- 29

## 



## An  o p e ra to r is a  

- s y mb ol 
- th a t t e lls R t o  pe r fo rm  so me  
- so r t o f o pe r a tio n.

## T yp e s o f O p e ra t or s

- :

## ma t h (a rit h me ti c)



## lo gica l (co mp are  valu es)



## a ssign me nt  (sa ving  valu es t o o bje ct s)



## e xtr act io n (t a ke o ut / re pla ce p art s o f o bje ct s)

- 30

## Op er at or s

- ht t ps: // ww w. sta tme th ods. ne t/ man age ment / ope rat ors. ht ml
- Typ e
- Wh at itdo es
- Symb ol(s)
- Arithmetic
- Math on numbers
- + 
- -
- * /^
- Logical
- Comparesv alues
- >  < = = != & |
- Ass ignment
- Ass igns valuest oobjec ts
- <
- -
- Ext rac tion
- Tak e out orreplac epart of an 
- object
- []$ 
- 31

## Ar i th me ti cop er a tor s



## Do e s ma th :



## Ad d :  2  

- + 
- 2

## Su b t r act :  3  

- -
- 1

## M u lt ip ly: 4  

- * 
- 4

## Divi de :  5  

- / 
- 2

## Exp o n e n t:  5

- ^
- 2

## Ctr l/

- Cm d +E n te r
- to  ru n

## Re su lts in  th e  Co n so le

- 32

## Exa m pl e: Wh ol e fta l ar ge r Tip ?



## b ill at  S ha ke S ha ck came  ou t t o  $2 5



## He t ip s1 5%



## 



## He t ip s1 2%



## Use  op era t or st o  calcu lat e  ho w much  Lo uie  an d 

- L ou be rt o
- t ip pe d
- 33

## Fun cti on s



## Form orec omplicatedtas ks, R 

- alsoc omespre
- -
- inst alledw itha 
- variety off unc tions.

## Funct ions area

- sequenceof 
- inst ruc tionst hat perf orm atas k

## Hav e 

- names

## Acc ept  

- arg umen ts
- (input )

## Ret urna 

- value
- (output)
- I n p u t
- O u tp u t
- ro u n d
- (
- x
- =  3. 1 4 1 5 9 ,   
- d i g i ts  
- =  0)
- 3
- 34

## Ar g um en ts



## To fi ndout what

- ar gu men ts
- a 
- func ti ont akes , lookup i t shelp 
- fi le( t y pe 
- ?r oun d)

## Som earg ument sar ereq ui red,  

- som eare opt i onal.

## You cans eet hat

- di git s
- i s 
- 6b‰ ë 6%Ty ¡…T€}¡ Ê ”6%¬ ‰
- need to i nclude i t andy ouw ill 
- g et the same outp ut
- 35
- In put
- Outpu t
- ro u nd
- (
- x
- = 3. 141 59,  
- d ig i ts 
- = 0
- )
- 3
- ro u nd
- (
- 3. 14 159
- )
- 3

## Ar g um en ts



## 5 ‰¡… à%ë …TÊ” 6%¬‰¡½ ¡%

- need to wri t eout t henam esof 
- t hearg ument s (
- x
- , 
- di g i ts
- ) i f 
- v aluesar ei nt hec orrec t ord er

## 6Á ¡½¡m lë ‰¬ }˜ €…à ¡T}ë ¡m‰ 

- under st andy our cod ewhen 
- y ouwr i te out the nameof the 
- arg ument
- 36
- In put
- Outpu t
- ro u nd
- (
- x
- = 3. 141 59,   
- d ig i ts 
- = 2)
- 3. 14
- ro u nd
- (
- 3. 14 159
- ,   
- 2
- )
- 3. 14

## Assi g nm en to pe ra to r



## Sa ve s 

- v a lue s
- in to  
- o bje c ts

## o bj e c t

- <
- -
- v a lue

## we i gh t_ k g

- <
- -
- 55

## O ve rw rite s p re vio u s va lu e s



## Ca n  b e co m b in ed  with  o the r  

- o p e ra to rs

## we i gh t_ l b

- <
- -
- 2 . 2
- *
- we igh t_ k g
- <
- -
- (
- a l t/ o pt i on  
- -
- d as h )
- 37

## N am i ng Ob j ects



## O bj ec tn am es:



## ca nn o ts tart wi th a di gi t



## ca nn o tco n tai n certa in  oth er 

- ch ar acter s su ch as a co mma  
- o r a sp ace.

## Ti

- p s:

## M ak ei t 

- a sd esc rip ti ve as  
- p os si bl e

## U

- se u nd ers cor es to mar k 
- sp a ces
- #t hi si sg ood
- w ei gh t_k g
- <
- -
- 55
- #n ot t he se
- w ei gh tkg
- !
- <
- -
- 55
- w ei gh t in  kg
- <
- -
- 55
- b la h
- <
- -
- 55
- 38

## W he re ar e my ob je cts?



## Y ou  can se e yo ur o bj ect s in 

- t he  wor kspa ce (t o p ri gh t 
- p an e of  
- Rst u dio
- )

## Y o u ca n al so get al ist in go f  

- th eseo b j ect swi th  
- c o mma nd s:

## l s()



## o bj ects ()

- 39

## C he cki ng Va l ue sof an Obj e ct



## I f  you w an t t o i nsp ect  t he  

- va lue s of  an  ob ject ,  t ype  
- t he  na me o f  th e o bje ct  in 
- t he  con sole
- weigh t_kg
- <
- -
- 55
- we igh t_ k g
- 40

## Exa m pl e: Wh ol e fta l ar ge r Tip ?



## b ill at  S ha ke S ha ck came  ou t t o  $2 5



## He t ip s1 5%



## 



## He t ip s1 2%



## Use  th e a ssign me nt  op er at o r t o save  ho w mu ch Lo ui e 

- a nd  
- L ou be rt o
- t ip pe d (cr ea te  6 o bje ct s)
- 41

## R em o vin g Obj e cts



## S om et ime s whe n yo u h ave  

- Rst u dio
- o pe n f or a  whi le,  
- yo ur wo rksp ace  ge ts 
- clu t te re d u p wit h o bj ect s

## Y ou  can r em ove o bj ect s 

- wit h  comm an ds (r igh t ) or  by 
- clicki ng t h e b roo m ico n in

## E nvir on me nt  

- p an e
- # rem ove  ob ject  cal led  y
- rm
- (
- y
- )
- # rem ove  eve ryt hin g in  you r 
- wo rksp ace
- rm
- (
- list  
- =
- ls
- () )
- 42

## Ob j ects: No tJu stfo r Sto ri n gN u mb er s

- 43
- t y pe
- x
- <
- -
- 32
- n u me r ic
- y
- <
- -
- "h i"
- ch a ra cte r

## Ba sic Da ta  t ype s:



## Ch a r acte r



## Nu m e ric



