---
title: "Lecture 4: Summarizing Data"
format: html
---

Econ 1 06

Lec tur e 4

Fal l 2024

L ar ge p ar t of t he s e s l i d es  a re a d ap t ed  fro m Ni ck  Ha ge rt y a t M on ta na  St a te  

U n i ve rs i t y a nd

In t rod uc ti o n t o Da t a S cie nce

b y R af ae l A. Iri z ar ry, us e d  und e r

C C  B Y

-

NC

-

S A 4.0

, 

a nd

©T ‰ T …ë ¡ %…¡ É6m… 6% 6˜ë } ‰ } ª

b y Gr an t R . Mc De rmo t t, us e d  und e r th e

M IT  

L ice ns e

.

R em i nd er s

L ab 1  will b e p ost ed  Su nd ay,  d ue o ne  wee k lat e r

on e

-

pa ge wri te up wi th t ab les

R scrip t

2

h tt ps:/ /

p o lle v.co m

/

vso ve ro

#

ti d ytue sda y

3

da tas our ce

co de tog ene rate gra ph

Ou tl i ne

su m ma r y ta b le s

fr eq u e n cy ta b le s

4

f ilt er

()

5

a rrang e

()

s ele ct

()

mut at e

()

R eca p: key 

d pl yr

ve rb s

* * The re  are  f ive ke y 

d plyr

ve rbs

t ha t  you n ee d t o l ea rn. * *

1.

f ilt e r

:  Filt e r (i. e . su bse t ) ro ws ba sed o n t h eir va lu es.

2.

a rra ng e

:  Ar ra ng e (i. e . r eo rd er)  row sb ase d o n t he ir va lue s.

3.

se lect

:  Se le ct ( i. e.  sub set ) co lum ns b yt h eir  na mes:  

4.

mu t at e

:  Cre at e n ew co lu mns.

5.

su mma rize

:  Col lap se mu lt ip le ro ws in to  a sin gle  sum mar y 

va lue

9

h tt ps: //

p o lle v. co m

/

vso ve ro

Su m ma ri zi n gV ar i ab le s

Ho w can  we su mma rize / de scrib e var iab le s?

qu ant it at ive d at a

cat eg orica l dat a

10

U sef ul fu ncti o nsf or qu an ti ta ti veva ri a bl e s 

Ce nt e r:

me an

() ,

me di an

()

S pr ea d:

sd

() ,

va r

()

Ra ng e:

mi n

() ,

ma x

() ,

P osit io n:

f irst

() ,

la st

() ,

To t al:  

su m

()

11

C r ea ti ng asu m ma ry tab l e

C r ea ti ng asu m ma ry tab l e

s um ma r ize

()

Ar gu me n ts

:

a  sp eci fi csu m m ar y st a ti sti c

e . g .:  

m ea n

( ), 

m in

( ), 

m ax

( ),  

m ed ia n

( ), 

s um

()

Out p ut

: a ta b le  with  th e  ca lcu la ted  su m ma r y sta tistic

C r ea ti ng asu m ma ry tab l e

he igh t_su mm ar y

<

-

st arw ars

% >%

su mm ar ize

(

m ean _he ight

=

m ean

(

he igh t

))

th esu mm ariz efu nct ion is 

si mila rto the mu tate fun ctio n

yo uh ave top rov ide ana me  

(

m ean _he ight

)f orw her eth e 

ne wi nfor mat ion will be stor ed

W ha tha pp en ed ?

h ei gh t_s um mar y

<

-

st arwa rs

%>%

su mm ari ze

(

mea n_h eig ht

=

me an

(

he igh t

))

M i ssin g Da ta i sWh at Ha pp en ed

o f a  nu mer ic vect o r if  th er e 

a re a ny mi ssing  valu es 

(N A)

W e will h ave  t o t ell i t t o  

ig no re t h e ro ws t ha t h ave  

mi ssing  valu es

16

Fi xed Wi th a nA dd it io na l Ar gu m en t

h ei gh t_s um mar y_w i tho u t_NA

<

-

st arwa rs

%>%

su mm ari ze

(

mea n_h eig ht

=

me an

(

he igh t,  

n a. rm

=

T RUE

))

Ba se R vs. 

D pl yr

W e coul d have a lso use d 

Base R f or t his cal cula ti on

T he cod e is act ual ly a bit  

simp ler

st ore t he in fo rmat ion a sa  

vect or

h e ig h t_ s u mma ry _ wi th o u t_ NA

<

-

me a n

(

s ta rw a rs

$

h e ig h t

,

n a .rm

=

T RU E

)

h e ig h t_ s u mma ry _ wi th o u t_ NA

<

-

st ar wa rs

%> %

s u mma ri ze

(

me a n _ h ei g h t

=

me a n

(

h e ig h t,  

n a .rm

=

T RU E

))

18

C r ea ti ng al e sssi l ly sum ma r ytab l e

W e can  sum mar ize m ore  t ha n on e va ria ble

A dd  a com ma , t h en w rit e o ut  t he  ne xt st a ti sti c

ht_and _wt_summary

<

-

st arw ars

%>%

summar ize

(

mean_height

=

mean

(

height  

,

na.rm

=

TR UE

)

,

mean_weight

=

mean

(

mass  

,

na.rm

=

TR UE

)

)

Exe r cise

Ca lcul at e m ed ian  an d me an  mass f o r cha ra cte rs in  Nab oo .  

W ha t d oe s th is sug ge st  ab ou t t h e di str ibu t ion  of  ma ss?

h t t ps: / /

p o lle v. co m

/

vso ve ro

Su m ma ri zi n gC a teg or i cal V ar i ab le s

Value

C ount

bel ow

1

av erage

6

hi gh

3

wa ge

Scor e

R ating

Ge nder

educ

11.4 2

3

av erage

mal e

16

3.91

3

av erage

fema le

12

8.76

3

av erage

mal e

16

7.69

4

abo ve

mal e

16

5

3

av erage

fema le

16

3.89

3

av erage

fema le

12

3.45

5

abo ve

fema le

12

4.03

4

abo ve

mal e

16

5.14

2

bel ow

mal e

17

3

3

av erage

mal e

16

Econ 1 01 reca p: w e summari ze/ descri be cat eg orica l varia ble sw it h 

f requ ency t abl es

C r ea tea fr eq ue ncy tab l e

c ou nt  

( ) 

Ar gu me n ts

:

a  ca te g o r ica l var ia b le

Out p ut

: a ta b le  with  th e  f re q u e n cyo f e a ch 

va lu e  of th e ca te g o rica l va r ia b le

22

Sp eci e sFre qu en cyTab l e

sp ec ie s_fr eq ue nc y

<

-

st arwa rs

%>%

co u nt

(

spe cies

)

23

Sp eci e sFre qu en cyTab l e( o rd er ed b y 

fr eq ue ncy)

sp ec ie s_c ou n t_o rd ere d

<

-

st arwa rs

%>%

co u nt

(

spe cies

)

%>%

ar ran g e

(

d esc

( 

n

))

24

Sp eci e sFre qu en cyTab l e( r em ove N A)

sp ec ie s_c ou n t_re mo ve_ NA

<

-

st arwa rs

%>%

co u nt

(

spe cies

)

%>%

ar ran g e

(

d esc

( 

n

))

%>%

fi lte r

(

!

i s. na

(

spe cies

))

25

Sh or te ni n go ur ta bl e sw it h 

s lice

()

sli ce _hea d

(

n

)

s e le ct  the  fi rs t n r ows

sli ce _ta i l

(

n

)

s elect  the las t n r ows .

sli ce _sa mple

(

n

)

r and omly s el ec t n r ows .

sli ce _min

(

x

, 

n

)

s e le ct  n row s wi th t he s mal le st va lue s of 

var i abl e x

sli ce _max

(

x

, 

n

)

s e le ct  n row s wi th t he l arg es t val ue s of 

var i abl e x

26

Top 1 0L i stof Mo stFr eq ue nt Spe ci es

to p_ ten _sp ec ie s

<

-

st arwa rs

%>%

fi lte r

(

!

i s. na

(

spe cies

))

%>%

co u nt

(

spe cies

)

%>%

ar ran g e

(

d esc

( 

n

))

%>%  

sl i ce_ he ad

(

n

=10 )

27

Exe r cise

f ilt er ou t missi ng val ues of  eye col or

ord er th e eye col ors in a f requ ency t abl e fro mh igh est t o lo west  

f requ ency

rep ort t he t op t en e ye colo rsb yf req uen cy

28

Fr eq ue ncyTa bl e (tw o var i ab l es)

sp ec ie s_g en d er_ freq u en cy

<

-

st arwa rs

%>%

co u nt

(

spe cies,  gen der

)

29

R eca p sofa r :H ow to  

Su m ma ri ze /D escr i be Va ri a bl e s

Q uant i tat i vevar i ab les: 

m e an, m e di an, e tc.

use  

su mm ari ze

()

C

at e gor ic al var i ab le s:

f requ enci es (use

co u nt

())

30

gr ou p_ by

()

31

Gr ou pe d sum ma r ytab l e

g ro up _b y

()

Ar gu me n ts

: se t o f va ria b le s

Out p ut

: a ta b le  with  th e  ca lcu la ted  su m ma r y sta tistic f o r 

e a ch co m b in a ti on  o f  un iq u e  va lu es in  t h e va r ia b le s in sid e 

g ro up _b y

()

Gr ou pe d sum ma r ytab l e 

w ei gh t_b y_ sex

<

-

st arwa rs

%>%

g ro up _b y

(

sex

) 

%>%

su mm ari ze

(

mea n_w t

=

me an

(

mass

,

n a. rm

= TR UE))

Out p ut

Gr ou pe d sum ma r ytab l e( m or e tha no ne  

g ro up ) 

w ei gh t_b y_ ge nd er _se x

<

-

st arwa rs

%>%

g ro up _b y

(

ge nde r

,

sex

) 

%>%

su mm ari ze

(

mea n_w t

=

me an

(

mass

,

n a. rm

= TR UE))

Out p ut

w hat hap pen edh ere ?

Using 

g ro up _by

() toCr eatea Fr equency Table

ch ar acte rs_ by _h om ew or ld

<

-

st arwa rs

%>%

g ro up _b y

(

ho mewo rld

) 

%>%

su mm ari ze

(

cou nt

=

n

())

Exe r cise

t id ytu esd ay

ch alle ng e

we  will u se t he  

rea d_ cs v

()  fu nct io n f ro m t he  

t id yverse

p acka ge

it  can  re ad i n csv f iles f ro m yo ur co mp ut er  or f ro m a  

URL

ti d ytue sda y

d ata

37