---
title: "Lecture 2: Vectors and Data Frames"
format: html
---

Econ 1 06

Da ta An alysi si n 

Econ omics

Fal l 2024

Lec tur e 2

Ba sedo n: 

ht tp: // ww w. dat acar pent ry. or g/R

-

ecol ogy

-

l esson/

R em i nd er s

P oll E ve rywh ere  is pr act ice t h is wee k,  ne xt we ek co un t s 

t ow ard s you r gr ad e

P lea se r eme mb er t o  log  in a t t h e be gi nn ing  of  ea ch le ct ure :

P ollE v.c om/ vs over o

2

#

ti d ytue sda y

weekly datac hallengeusingR

every Tuesdayanew 

challenge ispost ed 

here

Thedata us ed inthis example 

canbef ound 

here

youc an brow setheresult son 

soc ial media (#

tidy tuesday

)

Good sourc eofins pirationf or 

yourprojects

3

Ou tl i ne

Ve cto r s

Pa cka g e s

Da ta  Fr a me s

4

Ob j ects

Objects

st ore dat a(information)

Weus e theass ignment operator

<

-

to savev alues intoobjects

we igh t_ k g

<

-

55

5

Ob j ects: No tJu stfo r Sto ri n gN u mb er s

6

t y pe

x

<

-

32

n u me r ic

y

<

-

ch a ra cte r

Ba sic Da ta  t ype s:

Ch a r acte r  

Nu m e ric

D at astr u ctur es

 

o ne va lu e st or ed i n on e o bje ct

R h a s mo r e co m p le x da ta  st ru ctu re s t h a t m a ke  

wo r kin g w ith m o re  co m pl ex d a ta e a sie r :

Vec tor s

: mu lt ipl e valu es of t he sa me typ e.

Da ta f r am e

:  mu lt iple  

v ec tor s 

o f t h e sam e le ng t h gr ou pe d 

a sco lu mns.

7

Ve cto rs: Obj e ctsw i thM u lt ip l eV al u es

8

R ca n st or e mu lt ipl e 

va lue s of  t he sa me  typ e 

in  a da t a t ype  call ed a  

ve cto r.

A n o bje ct w it h a sin gl e 

e lem en t is a ct ua lly a 

ve cto r (l en gt h 1 ):

x

<

-

12.3

C r ea ti ng Obj e ctsW it hM ul ti p l eV al ue s

Just  like o th er obj ect s, 

vect ors are a ssign ed val ues 

usi ng t he assi gnme nt  

op erat or

T o assig n mult ip le val ues t o 

t he ob ject , w e use t he 

comb ine f un cti on 

c

() 

Each va lue i sse para te d by a 

comma

9

# Exa m p le : a  ve ctor  o fa g e s

a ge

<

-

c

(

30

,

40

,

25

,

22

)

P ol lEv.c om/v s o ve r o

C r ea ti ng Obj e ctsW it hM ul ti p l eV al ue s

Co m b in e f u n ctio n 

c

( ) :

Inp ut

: va lu es 

se p a ra te d b y 

co m ma s

Out p ut

: a ve cto r  

o b je ct

Al l th e  sa me  d a ta 

typ e

# Exa m p le : a  ve ctor  o fa g e s

a ge

<

-

c

(

30

,

40

,

25

,

22

)

10

C r ea ti ng Obj e ctsW it hM ul ti p l eV al ue s

fo r ch a r acte r  vecto r s, 

u se  str a ig h tq u o te s 

a r ou n d  t he  va lu e s

Si ng le  o r d o u b le  is 

fin e

#Exa mple : a cha ract er vect or of f avo rit e 

an imal s

an i mal s

<

-

c

(

"c at"

,

"d o g"

,

"d o g"

,

"d o g"

)

#T hi sa lso wo rks

an i mal s

<

-

c

(

' cat'

,

' do g '

,

' do g '

,

' do g '

)

11

Fun cti on sfo r in spe cti ng ve ctor typ e

R au to mat ical ly record sw hat  

t ype of  dat a is st ored i n an 

ob ject

He lp fu l fu nc tio n s:

cl ass

()

t ypeof

()

c la ss

(  ) 

t y pe of

(  )

x

<

-

32

n u me r ic

d o u bl e

y

<

-

"h i"

ch a ra cte r

ch a ra cte r

12

C l assC o er ci on

A ve cto r can 't mix a nd  

matc h ty pe s, so Rwi ll 

ch oose a ty p et hat ap pli e s 

to most v alu es(c lass 

co er ci on )

So meti mes thi s cho i ce 

ë }%¬ ‰6 y½ ë 6€‘€}€ TÊ 

ch ar acte r )

Us e 

class

()to seewhat R 

pick ed

#Whatt ypesaret hes e vect ors ?

fir st_vecto r

<

-

c

(

1, 2, 3, "a" 

)

second _vector

<

-

c

(

1, 2, 3, "4" 

)

13

Su m ma ri zi n gN u me ri cV ecto r s

Nume ric  ve ct or:

yo u can  com pu te  t he  

me an

14

#A vect or of  age s

ag e

<

-

c

(

30

,

40

,

25

,

22

)

#W ha t ha ppe ns whe n you t ryt o comp ut e 

t he mea n?

me an

(

ag e

)

H el p ful f un cti on sfor su mm a ri zi ng  

n um er i cvect or s

15

me an

()

me di an

()

ma x

()

mi n

()

sd

()

su mma ry

()

Su m ma ri zi n gch ar act er vect or s?

c har a cte r  ve cto r:

yo u will  

g et  war nin g m essa ge i f 

yo u t ry t o co mpu t e t he  

me an ,  med ia n,  min , m ax ()

I t  will re t ur n a va lue  of  NA  

(h ow R r eco rd sm issin g 

va lue s)

16

#a ch aract er vect or of  fa vorit e an imal s

an i mal s

<

-

c

(

"c at"

,

"d o g"

,

"d o g"

,

"d o g"

)

#W ha t ha ppe ns whe n you t ryt o comp ut e 

t he mea n?

me an

(

an i mal s

)

P ol lEv.c om/v s o ve r o

Fact or s

W e nee d to co nvert  th e ani mal 

vect or in to a  

fac tor , 

 

wa yo f st orin g cat ego rical d at a 

(vari abl es wit h a f ini te se t of  

cat eg orie s) 

we u se th e 

fac tor

() fu nct ion t o 

crea te a f act or vari abl e fro mt he  

an imal sve cto r

17

#a ch aract er vect or of  fa vorit e an imal s

an i mal s

<

-

c

(

"c at"

,

"d o g"

,

"d o g"

,

"d o g"

)

an i mal s_ facto r

<

-

fac tor

(

an i mal s

)

Fact or s

Y ou  can a lre ad y see  th at  

in f orm at io n wh en  an ima ls is 

st or ed  as a f a cto r in st ea d of  

a ch ar act e r vect o r

18

Su m ma ri zi n gFa ctor s

W e can  no w calcu la te  

su mma ry st at ist ics mo re  

a pp rop ria t e f or  

ca te go rica l da t a

19

Input

O u tp u t

l e v e l s

(

a n i m a l s _f ac to r

)

"c a t"  "d o g "

n l e v e l s

(

a n i m a l s _f ac to r

)

2

s u m m a ry

(

a n i m a l s _f ac to r

)

c a t   d o g  

1      3  

D at astr u ctur es: Ve ctor sto D ata Fr am es

20

W he n we h ave  mu lt iple  

p iece s of  inf o rma t ion  

f ro m t he  same  pe op le,  

 

t he  inf o rma t ion  st ore d 

a sa  sing le t a ble  vs 

in divi du al ve cto rs

30

40

25

22

ca t

do g

do g

do g

ve cto r

ve cto r

30

ca t

40

do g

25

do g

22

do g

da taf ram e

D at astr u ctur es: Ve ctor sto D ata Fr am es

21

Th is will a llo w us t o d o 

t hi ng su ch a s:

cal cula te a verag e age  

f or cat p eop le

cal cula te a verag e age  

f or dog p eop le

t he se t h ing s ne xt we ek 

30

ca t

40

do g

25

do g

22

do g

da taf ram e

D at astr u ctur es: Ve ctor sto D ata Fr am es

22

V ect o rs ar e t he  bu ildi ng  

b locks o f Da t a Fr ame s

D at afr a me s

Ro w s

=  ob se r va ti on s

Co lum ns

=  var ia b le s

Al l val ue s in  a  col um n  

m u st b e  t he  sa m e d a ta  

typ e . 

Al l col um n s mu st h a ve 

sa m e n u m be r  o f r o ws.

23

 

 

24

Pa ckag es

M any  of the mo stu sefu lf unc ti ons of Rc ome fr om ad d

-

on

p ack ag es .

Pa ckag es can i nc lud e:

reus ablefunc ti ons

t hedoc ument at i ont hat desc ri bes howt ouse them  

sam pled ata

So me ar ewe ll mai ntai ne d,  and o ther s ar e not (use r b ewar e)

25

Pa ckag es Exam p le

T hi nk of p ack age sas ap ps 

fo r y ou r p hon e

% }‰T ë ‰6 %…¡ l T%” ©6b ¡% ª

i t when y ou wan tto u sea  

p ack age i n y our  scr i pt

Imp or ta nt: y ou n eed t o 

lo ad the p ack age e ach ti me 

y ou op en RS tud i o

26

#r un thi so nce

in sta ll. pa ckage s

(

"

dsl abs

")

#r un thi se ver yt ime yo uo pen  

RS tud io

l ib ra ry

(

dsl abs

)

 

Loa d the  

d atase t

mu rd er s

fr o m 

th e 

d slab s

p ack age :

li br a ry

(

d sla b s

)

data

(

murders

)

27

 

Y ou  can a lre ad y see  

so me in f or mat io n 

a bo ut  t he d at a  fr am e:

51 o bserva ti ons

5 vari abl es

28

 

I f  you p re ss th e b lue  

o f t h e na me , yo u wi ll 

g et  mo re d et a iled  

in f orm at io n o n t he  

va ria ble s

29

 

Sa mei n for mati o n 

g ets sent to the  

co nsol ei f y ou  

ex amine i ts

s tr

uc tur e 

wi th the

st r

()  

f un ct ion

:

st r

(

mu rd er s

)

30

 

C

li ck o nt he 

d ataf ra me

i n y our  

Env i r on ment p ane to 

v i ew the d ataset i n 

ë ‰¬

en ti r ety

Y ou  can a lso t yp e:

vie w

(

mu rd er s

)

31

 

T he da tav i ewe r  

p r ov i de sa hel pf ul 

fi r st loo ka ty ou r d ata 

(y ou sho uld a lway s 

v i suall y i nsp ect y ou r 

d ata)

We ca na lso app ly  

some e asy p oi nt and  

cl ic k tool sto  

sor t/ fi lte r i n the  

v i ewer

32

So r ti ng i nth e da tavi e w er

you c an s or t by any 

c olum n by just  by c li ck i ng  

on t hec ol umn

 

alr ead ys or ted t o rever se 

t he s or t di r e c ti on

33

Fi l ter i ng i nt he da ta vie w er

To ap ply fi lt er s ,c li c k  the  

F i lter  ic on i n t het oolb ar

An yfi e ld t hat c an b e  

fi lt ered wi ll ha ve a whi t e 

b ox lab eled

All

34

P ol lEv.c om/v s o ve r o

Fi l ter i ng i nt he da ta vie w er

If you c li c k o n an ume r ic  

var i abl e, a hi s togr am wi ll 

p op up wh er e you ca n 

s e le ct  the  value s yo uw ant  

t of il te r fo r

35

Fi l ter i ng i nt he da ta vie w er

F i lte r i ng/ s or ti ng i n th e 

d ata vi ewer d oes not  mak e 

an yp erma nent c han ges t o 

t he mu rd e rs  dat a fra me  

F or ex amp le, i f you r eo pen 

t he vi e we r af te r fi lt e ri n g 

for  the  Sout h, all of the  

r egions w il ls t il lb et her e

36

Fun cti on sfo r Insp ecti n gd at afr a me s

* Also  

in spect s 

vect ors

F un cti o n

O utp u t

cl as s

*

Cl ass of t he o bje ct

str

*

st ruct ure:  # ro ws, co ls, d at a typ es

h ead

/

tai l

*

lo ok at f irst / last  6 rows (al l colu mns)

n ro w

/

n co l

nu mber of  rows/ col umns

n ame s

col umn na mes

su mm ary

*

summa ryst at s fo re ach col umn (min , max,  et c.)

37

Su m ma ry Sta ti sti cs

Disp lay so me 

summa ry  stati sti cs 

with

su mma ry

() 

fu nct io n:

su mma ry

(

mu rd er s

)

38

Su m ma ry Sta ti sti cs(n um e ri c)

su mma ry st at s f or  

n ume ric ve ct ors:  

min , max

qu art ile s

mea n

39

Su m ma ry Sta ti sti cs(f acto r)

su mma ry st at s f or  

f act o r var iab le s: 

le vels (cat eg orie s)

f requ enci es of e ach 

le vel

40

Su m ma ry Sta ti sti cs(ch ar a cter )

su mma ry st at s f or  

ch ara ct er ve ct or s: n ot  

mu ch t o r ep or t

b et t er t o  sto re  

ca te go rica l da t a a sa  

f act o r

41

R ef er en ci ng Ve ctor si n aD a taFr am e

W euse the a

c cessor  

oper ator  

$

t orefer ence av ect or in adat a 

fram e

:

m urder s

$

pop ulati on

42

Exa m pl e: C he ckvecto r type i n ad ata  

fr am e

Y ou  can u se t h e acce ssor  

o pe rat o r 

$

co mbi ne d wit h  

cla ss

()  to  che ck th e ve ct or t yp e 

o f p op ula t ion

43

c l a s s

(

m ur d er s

$

p op ula ti o n

)

C r ea ti ng ne w vecto r sw it h 

$

44

m urd er_ rat e

<

-

m urd ers

$ 

to tal 

/

m urd ers

$ 

po pul atio n 

*

10 000 0

we cancreateanew 

vec tor(

murder_rate

) 

by ref erencing 

vec torsint he 

murders dataf rame

Ad di n ga ve ctor to a Da ta Fra me w i th 

$

45

m urd ers

$

m urd er_ rat e

<

-

m urd ers

$

to tal 

/

m urd ers

$

po pul atio n

*

10 000 0

addthenew vector 

to themurder dat a 

frame

P ol lEv.c om/v s o ve r o