
project:
  type: website
  output-dir: docs

website:
  title: "Econ 106 Test Site"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: lectures/lecture1.qmd
        text: Lecture 1

format:
  html:
    theme: cosmo
    toc: true
